version: '2'
services:
  droppy:
    container_name: droppy
    image: silverwind/droppy
    ports:
      - '8989:8989'
    volumes:
      - /media/user/downloads1/Share/droppy/config:/config
      - /media/user/downloads1/Share/droppy/files:/files
    restart: unless-stopped
